### ISSUE TITLE
missing field activeCell

### ISSUE THREAD

**Issue by mustafa0x** [zitsen/xlsx2csv.rs#15]
I get this error when running.

```
thread 'main' panicked at 'parse worksheet error: XmlDeError(Custom("missing field `activeCell`"))', /.../ooxml-0.2.5/src/document/spreadsheet/mod.rs:124:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by WingDust** [comment]
i also have 

```sh
thread 'main' panicked at 'workbook styles error: XmlDeError(Custom("missing field `builtinId`"))', /.../ooxml-0.2.7/src/document/spreadsheet/mod.rs:76:63
```

**Comment by zitsen** [comment]
Try [v0.4.5](https://github.com/zitsen/xlsx2csv.rs/releases/tag/v0.4.5)
